replicas: 2
service:
  nodePort: 30082
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 256Mi
image:
  repository: docker.io/antonychiu2/git-node-app-test2
  tag: sha-20e46059ddfeaaaaf86516dfafbb1aecf60ed843
# git-node-app application, prod environment SDK key (GS-7)
roxSdkKey: "82192033-9f2a-4839-87ae-f672e898c161"
