replicas: 2
service:
  nodePort: 30082
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 256Mi
image:
  repository: docker.io/antonychiu2/git-node-app-test2
  tag: sha-fe71976dc1ba211a1adc35af88b2f8a380ba060b
