replicas: 2
service:
  nodePort: 30082
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 256Mi
image:
  repository: docker.io/antonychiu2/git-node-app-test2
  tag: sha-f968e09d03561293519221061136f7c22a6e73a9
