apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.roxSdkKey }}
            - name: ROX_SDK_KEY
              value: {{ .Values.roxSdkKey | quote }}
            {{- end }}
          readinessProbe:
            httpGet: { path: /, port: {{ .Values.containerPort }} }
            initialDelaySeconds: 3
          livenessProbe:
            httpGet: { path: /, port: {{ .Values.containerPort }} }
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
